name: posh_boys_v3
description: "A Flutter app for The Posh Boys Bar, featuring events, drinks, and more."
publish_to: "none" # Prevents accidental publishing to pub.dev

# Flutter SDK version
environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies for the app
dependencies:
  flutter:
    sdk: flutter

  # Networking (API calls)
  http: ^1.3.0  # Latest version for handling API requests

  # Date formatting
  intl: ^0.20.0  # Useful for formatting dates (e.g., UK format dd/MM/yyyy HH:mm)

  # HTML string parsing
  html: ^0.15.4
  flutter_html: ^3.0.0-beta.2
  
  # State management (optional, for better app structure)
  provider: ^6.0.5  # Lightweight state management for dynamic data

# Development dependencies (for debugging, testing)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Fonts (Optional: If you want a custom font like Montserrat)
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
